### ISSUE TITLE
Random Crash

### ISSUE THREAD

**Issue by swarshah** [SwarShah/hyper-custom-touchbar#14]
For whatever reason plugin fails to get the current session and thus fails to write to the terminal.

Currently, there are no reproducible steps but it happened when Hyper had multiple windows and multiple tabs open in each one.

Exception details:
```
Uncaught Exception:
TypeError: Cannot read property 'write' of undefined
    at writeToTerminal (/Users/swar/.hyper_plugins/node_modules/hyper-custom-touchbar/index.js:112:43)
    at Object.click (/Users/swar/.hyper_plugins/node_modules/hyper-custom-touchbar/index.js:95:13)
    at TouchBarButton._addImmutableProperty (/Applications/Hyper.app/Contents/Resources/electron.asar/browser/api/touch-bar.js:205:16)
    at BrowserWindow.interactionListener (/Applications/Hyper.app/Contents/Resources/electron.asar/browser/api/touch-bar.js:109:14)
    at BrowserWindow.emit (events.js:182:13)
```

**Comment by wdanilo** [comment]
I've got the same issue constantly right now. No button just works and it throws this error after every press.

**Comment by swarshah** [comment]
@wdanilo I just published a version with the fix and it should be fixed now. You'll probably have to restart your Hyper to get it updated.
